name: Test

on:
  pull_request:
  push:
    branches:
      - gh-pages

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

# Остальные jobs (build и deploy) остаются без изменений
jobs:
  build: # Job для сборки проекта
    runs-on: ubuntu-latest # Указываем среду выполнения
    needs: lint # Зависимость от job 'lint'
    steps:
      - uses: actions/checkout@v2 # Клонирование репозитория
      - uses: actions/setup-node@v1 # Установка Node.js
        with:
          node-version: 22.x # Указываем версию Node.js
      - run: npm ci # Установка зависимостей
      - name: Build # Шаг сборки
        run: npm run build # Выполняем сборку проекта
      - name: Validate HTML # Шаг валидации HTML
        run: npm run validate-html # Валидация HTML файлов
      - name: Minify HTML # Шаг минификации HTML
        run: npm run minify-html # Минификация HTML файлов
      - name: Minify CSS # Шаг минификации CSS
        run: npm run minify-css # Минификация CSS файлов
      - name: Minify JS # Шаг минификации JavaScript
        run: npm run minify-js # Минификация JavaScript файлов

  deploy: # Job для деплоя
    runs-on: ubuntu-latest # Указываем среду выполнения
    needs: build # Зависимость от job 'build'
    steps:
      - uses: actions/checkout@v2 # Клонирование репозитория
      - name: Deploy to GitHub Pages # Шаг деплоя на GitHub Pages
        run: |
          npm install -g gh-pages # Установка пакета gh-pages
          gh-pages -d dist # Деплой из директории dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Токен для доступа к GitHub
